spring.application.name=assettrack
spring.datasource.url=jdbc:mysql://localhost:3306/assettrack_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true